accounts/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),

    path('password_reset/', PasswordResetView.as_view(template_name='password_reset_form.html', email_template_name='password_reset_email.html', success_url='/accounts/password_reset_done'), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/accounts/reset/done'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('profile/<int:user_id>/', views.user_profile, name='userProfile'),
    path('profile/set_user_description/', views.set_user_description, name='setUserDescription'),
]

bsamsonapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from dashboard import views

urlpatterns = i18n_patterns (
    path('', login_required(views.index)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('task/', include('task.urls')),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    path('add-project/', addProject, name='addProject'),
    path('add-skill/', addSkill, name='addSkill'),
    path('add-formation/', addFormation, name='addFormation'),
    # path('calendar/', views.xxx, name='calendar'),
    # path('projects/', views.xxx, name='projects'),
    # path('profile/', views.xxx, name='profile'),

]

task/urls.py
from django.urls import path

from task import views

app_name = 'task'
urlpatterns = [
    path('<int:task_id>/', views.task, name='task'),
    path('add_task/', views.addTask, name='addTask'),
    path('set_task_status/', views.setStatus, name='setTaskStatus'),
    path('set_task_description/', views.setDescription, name='setTaskDescription'),
    path('delete_task/', views.deleteTask, name='deleteTask'),
    path('add_step/', views.addStep, name='addStep'),
    path('set_step_status/', views.setStepStatus, name='setStepStatus'),
    path('delete_step/', views.deleteStep, name='deleteStep'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.CharField(default='media/profile_picture/default.png', max_length=100)
    description = models.CharField('Description', blank=True, null=True, max_length=500)
    job = models.CharField('Job', blank=True, null=True, max_length=40)

    def __str__(self):  
        return "{}".format(self.user)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.validators import UnicodeUsernameValidator as username_validator

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, widget=forms.TextInput(attrs={"placeholder": "Nom d'utilisateur"}))
    password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={"placeholder": "Mot de passe"}))

class SignupForm(UserCreationForm):
    username = forms.CharField(
        max_length=150,
        help_text=('Obligatoire. 150 caractères ou moins. Lettres, chiffres et @/./+/-/_ uniquement.'),
        validators=[username_validator],
        error_messages={'unique': ("A user with that username already exists.")},
        widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "Nom d'utilisateur"})
    )
    email = forms.EmailField(
        max_length=50, 
        help_text='Obligatoire. Renseignez une adresse email valide.', 
        widget=(forms.TextInput(attrs={'class': 'form-control', "placeholder": "Adresse email"}))
    )
    password1 = forms.CharField(
        help_text="Votre mot de passe doit contenir au moins 8 caractères et ne peut pas être entièrement numérique.", 
        widget=(forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Mot de passe"}))
    )
    password2 = forms.CharField(
        help_text=('Entrez le même mot de passe, pour vérification.'), 
        widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Confirmer le mot de passe"})
    )
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email')

class UserPictureForm(forms.Form):
    file = forms.FileField(label='', widget=forms.FileInput(attrs={"placeholder": "Nom d'utilisateur", "accept": "image/*"}))

accounts/views.py
from distutils import extension
from django.conf import settings
from django.contrib.auth import login, authenticate, logout
from django.http import JsonResponse
from django.shortcuts import redirect, render

from accounts.models import User, UserProfile
from dashboard.models import Project, Skill, Formation
from accounts.forms import LoginForm, SignupForm, UserPictureForm
from bsamsonapp.utils import *

def login_page(request):
    form = LoginForm()
    message = ''
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                try:
                    return redirect(request.POST.get("next"))
                except:
                    return redirect(settings.LOGIN_REDIRECT_URL)
                    
            else:
                message = 'Identifiants invalides.'
    return render(request, 'accounts/login.html', context={'form': form, 'message': message})


def signup_page(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user)
            # auto-login user
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
    return render(request, 'accounts/signup.html', context={'form': form})

def logout_page(request):
    logout(request)
    return redirect(settings.LOGIN_URL)

def user_profile(request, user_id):
    try:
        userProfile = UserProfile.objects.get(pk=user_id)
    except:
        userProfile = UserProfile.objects.create(pk=user_id, user=User.objects.get(pk=user_id))
        userProfile.save()

    context = { 
        'userProfile' : userProfile,
        'projects': Project.objects.filter(user=User.objects.get(pk=user_id)),
        'skills': Skill.objects.filter(user=User.objects.get(pk=user_id)),
        'formations': Formation.objects.filter(user=User.objects.get(pk=user_id)),
        'form' : UserPictureForm()
    }

    if request.method == 'POST':
        form = UserPictureForm(request.POST, request.FILES)
        if form.is_valid():
            fileExtension = request.FILES['file'].content_type.rsplit('/', 1)[-1]
            filePath = 'media/profile_picture/profile_picture_{}.{}'.format(user_id, fileExtension)
            userProfile.picture = handle_uploaded_file(filePath, request.FILES['file'])
            userProfile.save()
            context['userProfile'] = userProfile

    return render(request, 'accounts/user_profile.html', context)

def set_user_description(request):
    userProfile = UserProfile.objects.get(pk=request.POST.get("userId"))
    userProfile.description = request.POST.get("userDescription")
    userProfile.save()

    return JsonResponse({
        "userProfileDescription": userProfile.description,
    })

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}


<div class="widget form">
    <h2>Connexion</h2>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <input type="hidden" value="" id="next" name="next">
        {{ form }}
        <!-- <a class="forgotPassword" href="{% url 'accounts:password_reset' %}">Mot de passe oublié ?</a> -->
        <p>{{ message|title }}</p>
        <div>
            <a class="button" href="{% url 'accounts:signup' %}">S'inscrire</a>
            <button class="button callToAction" type="submit">Connexion</button>
        </div>
    </form>
</div>

<script>
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = window.location.search.substring(1),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return typeof sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
            }
        }
        return false;
    };
    console.log(getUrlParameter('next'))
    $('input#next').val(getUrlParameter('next'));
</script>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="widget">
  <p>
    Votre mot de passe a bien été changé. Vous pouvez continuer et vous connecter maintenant.
  </p>
  <div>
    <a class="button callToAction" href="{% url 'accounts:login' %}">Se connecter</a>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
  {% if validlink %}
  <h2>Changer le mot de passe</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <div>
      <a></a>
      <button class="button callToAction" type="submit">Confirmer</button>
    </div>
  </form>
  {% else %}
  <p>
    Le lien de réinitialisation du mot de passe n'était pas valide, peut-être parce qu'il a déjà été utilisé.
    Veuillez demander une nouvelle réinitialisation du mot de passe.
  </p>
{% endif %}
</div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
  <p>
    Nous vous avons envoyé par e-mail des instructions pour définir votre mot de passe, 
    si un compte existe avec l'e-mail que vous avez saisi.
    Vous devriez les recevoir sous peu
  </p>
  <p>
    Si vous ne recevez pas d'e-mail, assurez-vous d'avoir entré l'adresse avec laquelle vous vous êtes inscrit,
    et vérifiez votre dossier spam.
  </p>
</div>
  
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
Pour lancer le processus de réinitialisation du mot de passe pour votre compte Exide Lille : {{ user.get_username }},
cliquez sur le lien ci-dessous :

{{ protocole }}://{{ domaine }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Si cliquer sur le lien ci-dessus ne fonctionne pas, veuillez copier et coller l'URL dans un nouveau navigateur
fenêtre à la place.

Sincèrement,

L'équipe Exide Lille
{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
  <h2>Mot de passe oublié</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <div>
      <a></a>
      <button class="button callToAction" type="submit">Confirmer</button>
    </div>
  </form>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
    <h2>Inscription</h2>
    <form action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        <div>
            <a class="button" href="{% url 'accounts:login' %}">Se connecter</a>
            <button class="button callToAction" type="submit">S’inscrire</button>
        </div>
    </form>
</div>

{% endblock content %}

accounts/templates/accounts/user_profile.html
{% extends "base.html" %}

{% block content %}

<section class="widget userProfile">
    <span>
        <span class="editable">
            <img class="userPictureBig" src="/{{ userProfile.picture }}">
            {% if user.id == userProfile.user.id %}
                <i class="fi fi-sr-pencil set-user-picture">
                    <div class="hidden">
                        <form action="{% url 'accounts:userProfile' user.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form }}
                        </form>
                    </div>
                </i>
            {% endif %}
            </span>
        <h1>{{ userProfile|title }}</h1>
    </span>
    <br>
    <section class="description userDescription">
        <h2>Description</h2>
        {% if user.id == userProfile.user.id %}
            <form>
                {% csrf_token %}
                <textarea maxlength="500" user-id="{{ user.id }}" user-description="{{ userProfile.description }}" type="text" placeholder="Ajouter une description"></textarea>
                <input type="hidden">
                <div>Press enter to save</div>
            </form>
        {% else %}
            <textarea maxlength="500" user-id="{{ user.id }}" user-description="{{ userProfile.description }}" type="text" placeholder="Pas de description" readonly></textarea>
        {% endif %}
    </section>
</section>

<section>
    <h2>Projets {% if user.id == userProfile.user.id %}<a href="{% url 'dashboard:addProject' %}"><i class="fi fi-rr-add"></i></a>{% endif %}</h2>
    {% if projects|length == 0 %}
        <div class="widget">
            {% if user.id == userProfile.user.id %}
            <span class="nothingToDraw">Oh il semblerait que tu n'es rien à faire pour le moment, clique sur le<i class="fi fi-rr-add"></i>juste au dessus pour ajouter un projet !</span>
            {% else %}
            <span class="nothingToDraw">Oh on dirait bien que {{ userProfile|title }} n'a malheureusement pas encore de projet.</span>
            {% endif %}
        </div>
    {% else %}
        <div class="cards">
            {% for project in projects %}
            <a class="card" href="{{ project.id }}">
                <img class="" src="/{{ project.picture }}">
                <h2>{{ project.name }}</h2>
                <p>{{ project.description }}</p>
            </a>
            {% endfor %}
        </div>
    {% endif %}
</section>

<section>
    <h2>Compétences {% if user.id == userProfile.user.id %}<a href="{% url 'dashboard:addSkill' %}"><i class="fi fi-rr-add"></i></a>{% endif %}</h2>
    <div class="skills widget">
        {% if skills|length == 0 %}
            {% if user.id == userProfile.user.id %}
                <span class="nothingToDraw">T'as forcément au moins une compétence, clique sur le<i class="fi fi-rr-add"></i>et ajoutes en !</span>
                {% else %}
                <span class="nothingToDraw">{{ userProfile|title }} n'a pas renseigné ces compétences pour l'instant.. &#x1F622;</span>
            {% endif %}
        {% else %}
            {% for skill in skills %}
            <a class="skill">
                <h2>{{ skill.name }}</h2>
            </a>
            {% endfor %}
        {% endif %}
    </div>
</section>

<section>
    <h2>Formations {% if user.id == userProfile.user.id %}<a href="{% url 'dashboard:addFormation' %}"><i class="fi fi-rr-add"></i></a>{% endif %}</h2>
    {% if formations|length == 0 %}
        <div class="widget">
            {% if user.id == userProfile.user.id %}
            <span class="nothingToDraw">Tu vas pas me faire croire que t'es pas formé à quelque chose, clique vite sur le<i class="fi fi-rr-add"></i>pour mettre à jour tes formations !</span>
            {% else %}
            <span class="nothingToDraw">{{ userProfile|title }} n'a aucune formation de référencer sur le site. Essaye peut être son linkedIn &#x1F937;</span>
            {% endif %}
        </div>
    {% else %}
        <div class="cards">
            {% for formation in formations %}
            <a class="card" href="{{ formation.id }}">
                <img class="" src="/{{ formation.picture }}">
                {% if formation.logo %}
                <img class="cardLogo" src="/{{ formation.logo }}">
                {% endif %}
                <h2>{{ formation.name }}</h2>
                <p>{{ formation.description }}</p>
            </a>
            {% endfor %}
        </div>
    {% endif %}
</section>

{% endblock %}