bsamsonapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from dashboard import views

urlpatterns = i18n_patterns (
    path('', login_required(views.index)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('task/', include('task.urls')),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    path('add-project/', addProject, name='addProject'),
    path('add-skill/', addSkill, name='addSkill'),
    path('add-formation/', addFormation, name='addFormation'),
    # path('calendar/', views.xxx, name='calendar'),
    # path('projects/', views.xxx, name='projects'),
    # path('profile/', views.xxx, name='profile'),

]

task/urls.py
from django.urls import path

from task import views

app_name = 'task'
urlpatterns = [
    path('<int:task_id>/', views.task, name='task'),
    path('add_task/', views.addTask, name='addTask'),
    path('set_task_status/', views.setStatus, name='setTaskStatus'),
    path('set_task_description/', views.setDescription, name='setTaskDescription'),
    path('delete_task/', views.deleteTask, name='deleteTask'),
    path('add_step/', views.addStep, name='addStep'),
    path('set_step_status/', views.setStepStatus, name='setStepStatus'),
    path('delete_step/', views.deleteStep, name='deleteStep'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.fields.CharField('Nom', max_length=100)
    picture = models.CharField(default='media/projects/default.png', max_length=100)
    description = models.fields.CharField('Description', blank=True, null=True, max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']


class Skill(models.Model):
    name = models.fields.CharField('Compétence', max_length=100)
    color = models.fields.CharField('Couleur', default='#06D7A0', max_length=7)
    value = models.fields.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-value']


class Formation(models.Model):
    name = models.fields.CharField('Nom', max_length=100)
    logo = models.fields.CharField(default='', max_length=100)
    picture = models.CharField(default='media/formations/default.png', max_length=100)
    description = models.fields.CharField('Description', blank=True, null=True, max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

dashboard/forms.py
from django import forms

from dashboard.models import Project, Skill

class ProjectForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Nom du projet"}),
    )
    picture = forms.FileField(
        help_text="Une belle image qui mettra bien en valeur ton projet !",
        widget=forms.FileInput(attrs={"accept": "image/*"})
    )
    description = forms.CharField(
        max_length=500,
        help_text="Facultatif, mais c'est quand même mieux pour comprendre le projet.", 
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Ajouter une description"}),
    )

    class Meta:
        model = Project
        fields = ['name', 'picture', 'description']

class SkillForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Nom de la compètence"}),
    )
    color = forms.FileField(
        widget=forms.TextInput(attrs={'type': 'color'}),
        help_text="C'est facultatif mais ça mettra un peu de couleur a ton profil !", 
    )
    value = forms.IntegerField(
        max_value=100,
        min_value=0,
        help_text="Une note entre 0 et 100 qui indique ton pourcentage sur cette compétence.", 
    )

    class Meta:
        model = Skill
        fields = ['name', 'color', 'value']

class FormationForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Nom du diplôme ou de la formation"}),
    )
    logo = forms.FileField(
        required=False,
        help_text="Logo : Facultatif, mais ça peut être sympa de leur faire une petite pub à ton école",
        widget=forms.FileInput(attrs={"accept": "image/*"})
    )
    picture = forms.FileField(
        help_text="Une belle image qui mettra bien en valeur ta formation et qui EN PLUS embellira ton profil !",
        widget=forms.FileInput(attrs={"accept": "image/*"})
    )
    description = forms.CharField(
        max_length=500,
        help_text="Facultatif, mais c'est quand même mieux pour comprendre le projet.", 
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Ajouter une description"}),
    )

    class Meta:
        model = Skill
        fields = ['name', 'logo', 'picture', 'description']

dashboard/views.py
from multiprocessing.sharedctypes import Value
from turtle import color
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from bsamsonapp.utils import handle_uploaded_file

from task.models import Task
from dashboard.models import Project, Skill, Formation
from dashboard.forms import ProjectForm, SkillForm, FormationForm

@login_required
def index(request):
    context = { 
        'tasks' : Task.objects.filter(users=request.user.id)
    }
    
    return render(request, 'dashboard/index.html', context)

@login_required
def addProject(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = Project.objects.create(name=request.POST.get("name"), user=User.objects.get(pk=request.POST.get("userId")))
            pictureExtension = request.FILES['picture'].content_type.rsplit('/', 1)[-1]
            picturePath = 'media/projects/project_{}.{}'.format(project.id, pictureExtension)
            project.picture = handle_uploaded_file(picturePath, request.FILES['picture'])
            project.description = request.POST.get("description")
            project.save()
            # return redirect('/projects/{}'.format(project.id))
            return redirect('/accounts/profile/{}'.format(request.POST.get("userId")))

    return render(request, 'dashboard/add_project.html', context={'form': form})

@login_required
def addSkill(request):
    form = SkillForm()
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = Skill.objects.create(name=request.POST.get("name"))
            skill.color = request.POST.get("color")
            skill.value = request.POST.get("value")
            skill.user = request.user.id
            skill.save()
            return redirect('/accounts/profile/{}'.format(request.user.id))

    return render(request, 'dashboard/add_skill.html', context={'form': form})

@login_required
def addFormation(request):
    form = FormationForm()
    if request.method == 'POST':
        form = FormationForm(request.POST, request.FILES)
        if form.is_valid():
            formation = Formation.objects.create(name=request.POST.get("name"), user=User.objects.get(pk=request.POST.get("userId")))

            pictureExtension = request.FILES['picture'].content_type.rsplit('/', 1)[-1]
            picturePath = 'media/formations/formation_{}.{}'.format(formation.id, pictureExtension)
            formation.picture = handle_uploaded_file(picturePath, request.FILES['picture'])

            try:
                logoExtension = request.FILES['logo'].content_type.rsplit('/', 1)[-1]
                logoPath = 'media/logos/logo_{}.{}'.format(formation.id, logoExtension)
                formation.logo = handle_uploaded_file(logoPath, request.FILES['logo'])
            except:
                pass

            formation.description = request.POST.get("description")
            formation.save()
            # return redirect('/projects/{}'.format(project.id))
            return redirect('/accounts/profile/{}'.format(request.POST.get("userId")))

    return render(request, 'dashboard/add_formation.html', context={'form': form})

dashboard/templates/dashboard/add_formation.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
    <h2>Ajouter une formation</h2>
    <form action="{% url 'dashboard:addFormation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="userId" value="{{ user.id}}">
        <div>
            <a></a>
            <button class="button callToAction" type="submit">Ajouter</button>
        </div>
    </form>
</div>

{% endblock content %}

dashboard/templates/dashboard/add_project.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
    <h2>Ajouter un projet</h2>
    <form action="{% url 'dashboard:addProject' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="userId" value="{{ user.id}}">
        <div>
            <a></a>
            <button class="button callToAction" type="submit">Ajouter</button>
        </div>
    </form>
</div>

{% endblock content %}

dashboard/templates/dashboard/add_skill.html
{% extends 'base.html' %}

{% block content %}

<div class="widget form">
    <h2>Ajouter une compétence</h2>
    <form action="{% url 'dashboard:addSkill' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="userId" value="{{ user.id}}">
        <div>
            <a></a>
            <button class="button callToAction" type="submit">Ajouter</button>
        </div>
    </form>
</div>

{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% block content %}
<section>
    <h2>Tâches <a href="{% url 'task:addTask' %}"><i class="fi fi-rr-add"></i></a></h2>
    <div class="tasks widget">
        {% if tasks|length == 0 %}
            <span class="nothingToDraw">
                Oh il semblerai que tu n'es rien à faire pour le moment, clique sur le<i class="fi fi-rr-add"></i>juste au dessus pour créer une nouvelle tâche !
            </span>
        {% else %}
            {% for task in tasks %}
            <a href="{% url 'task:task' task.id %}">
                <span>{{ task.name }}</span>
                <span class="progressBar">
                    <b></b>
                    <div class="progressContainer"><div class="progressValue" value="{{ task.progress }}"></div></div>
                </span>
            </a>
            {% endfor %}
        {% endif %}
    </div>
</section>
{% endblock %}