accounts/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),

    path('password_reset/', PasswordResetView.as_view(template_name='password_reset_form.html', email_template_name='password_reset_email.html', success_url='/accounts/password_reset_done'), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/accounts/reset/done'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('profile/<int:user_id>/', views.user_profile, name='userProfile'),
    path('profile/set_user_description/', views.set_user_description, name='setUserDescription'),
]

bsamsonapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from dashboard import views

urlpatterns = i18n_patterns (
    path('', login_required(views.index)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('task/', include('task.urls')),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from task import views

app_name = 'task'
urlpatterns = [
    path('<int:task_id>/', views.task, name='task'),
    path('add_task/', views.addTask, name='addTask'),
    path('set_task_status/', views.setStatus, name='setTaskStatus'),
    path('set_task_description/', views.setDescription, name='setTaskDescription'),
    path('delete_task/', views.deleteTask, name='deleteTask'),
    path('add_step/', views.addStep, name='addStep'),
    path('set_step_status/', views.setStepStatus, name='setStepStatus'),
    path('delete_step/', views.deleteStep, name='deleteStep'),
]

templates/base.html
{% load static %}
{% load i18n %}

<html>
    <head>
        <title>{% trans 'Dashboard' %}</title>

        <link rel="icon" href="{% static 'dashboard/img/favicon.ico' %}">

        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'dashboard/icons/css/uicons-regular-rounded.css' %}">
        <link rel="stylesheet" href="{% static 'dashboard/icons/css/uicons-solid-straight.css' %}">
        <link rel="stylesheet" href="{% static 'dashboard/icons/css/uicons-solid-rounded.css' %}">
        <link rel="stylesheet" href="{% static 'dashboard/css/app-container.css' %}" />
        <link rel="stylesheet" href="{% static 'dashboard/css/right-menu.css' %}" />
        <link rel="stylesheet" href="{% static 'dashboard/css/left-menu.css' %}" />
        <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}" />

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="module" src="{% static 'dashboard/js/script.js' %}"></script>
        <script type="module" src="{% static 'dashboard/js/time.js' %}"></script>
        <script type="module" src="{% static 'dashboard/js/popup.js' %}"></script>
        <script type="module" src="{% static 'dashboard/js/task.js' %}"></script>
        <script type="module" src="{% static 'dashboard/js/accounts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include './left-menu.html' %}
        <div class="app-container">
            {% block content %}{% endblock %}
        </div>
        {% include './right-menu.html' %}
</body>
</html>

templates/left-menu.html
{% load i18n %}

<div class="left-menu col-2">
    <section>
        {% if user.is_authenticated %}
        <section class="user">
            <h2>
                <span>
                    {{ user | title }}
                </span>
                <i class="fi fi-rr-angle-small-down"></i>
            </h2>
            <div class="popup">
                <a href="{% url 'accounts:userProfile' user.id %}"><i class="fi fi-rr-user"></i>{% trans 'See user profile' %}</a>
                <a href=""><i class="fi fi-rr-paper-plane"></i>{% trans 'Invite collaborators' %}</a>
                <div class="separator"></div>
                <a href="{% url 'accounts:logout' %}">{% trans 'Sign out' %}</a>
            </div>
        </section>
        <section id="menu">
            <!-- <h2>Menu <i class="fi fi-rr-add"></i></h2> -->
            <h2>{% trans 'Menu' %}</h2>
            <a href="/"><i class="fi fi-rr-home"></i>{% trans 'Dashboard' %}</a>
            <a href=""><i class="fi fi-rr-calendar"></i>{% trans 'Calendar' %}</a>
            <a href=""><i class="fi fi-rr-apps"></i>{% trans 'Projects' %}</a>
            <a href="{% url 'accounts:userProfile' user.id %}"><i class="fi fi-rr-user"></i>{% trans 'Profile' %}</a>
            <a href=""><i class="fi fi-rr-comment"></i>{% trans 'Messages' %}</a>
            {% if user.is_superuser %}
            <a href="/admin"><i class="fi fi-rr-settings"></i>{% trans 'Administration' %}</a>
            {% endif %}
        </section>
        {% else %}
            <section>
                <h2>{% trans 'Authenticate' %}</h2>
                <a href="{% url 'accounts:login' %}"><i class="fi fi-rr-following"></i>{% trans 'Login' %}</a>
                <a href="{% url 'accounts:signup' %}"><i class="fi fi-rr-user-add"></i>{% trans 'Sign up' %}</a>
            </section>
        {% endif %}
    </section>
    <section>
        <h4>2022 {% trans 'by' %} Basile SAMSON</h4>
        <h4>{% trans 'with' %} &#x1F496; {% trans 'for' %} David</h4>
    </section>
</div>

templates/right-menu.html
<div class="right-menu col-1">
    <section>
        <h2 id="today"></h2>
        <h1 id="time"></h1>
    </section>
    <section>
        <h2 id="loaction"></h2>
        <h1 id="temperature"></h1>
    </section>
</div>